name: Gutentag, World!

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Run
        run: zsh gutentag_world.zsh

      - name: Verify output
        run: bash test.sh
